force-app/main/default/objects/Adopter__c/Adopter__c.object-meta.xml
<CustomObject>
    <label>Adopter</label>
    <nameField>
        <label>Adopter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adopters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Adopter__c/fields/Warning__c.field-meta.xml
<CustomField>
    <fullName>Warning__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked it means that this adopter has returned an animal with no relevant reason.</description>
    <inlineHelpText>If checked it means that this adopter has returned an animal with no relevant reason.</inlineHelpText>
    <label>Warning</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Adoption__c/Adoption__c.object-meta.xml
<CustomObject>
    <label>Adoption</label>
    <nameField>
        <displayFormat>AD-{000}</displayFormat>
        <label>Adoption</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adoptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Adoption__c/fields/Flag__c.field-meta.xml
<CustomField>
    <fullName>Flag__c</fullName>
    <description>If green the adoption occurred succesfully, if yellow the animal returned to shelter with a relevant reason and if red the animal returned to the shelter with an invalid reason</description>
    <inlineHelpText>Check green if the adoption was completed succesfully, yellow if the animal returned to shelter with a relevant reason and red the animal returned to shelter with an invalid reason.</inlineHelpText>
    <label>Attention Flag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MarksAdopterWarning.cls
public with sharing class MarksAdopterWarning {
    
    //Filters the adoptions that are Red flagged
    public static List<Adoption__c> adoptionFilter(List<Adoption__c> listAdp, String flag) {
        
        List<Adoption__c> filteredAdoptions = new List<Adoption__c>();
        
        for (Adoption__c adp : listAdp){
            if (adp.flag__c == flag){
                filteredAdoptions.add(adp);
            }
        }    
        return filteredAdoptions;            
    }
    
    // Updates the Warning field on the Adopter object according to the Adoption Stage
    public static void marksAdopterWarning(List<Adoption__c> listAdp, boolean flag){
        
        List<Id> adoptersIds = new List<Id>();

        for (Adoption__c adoption : listAdp){
            adoptersIds.add(adoption.Adopter__c);
        }

        List<Adopter__c> adoptersList = [SELECT Warning__c FROM Adopter__c WHERE Id IN :adoptersIds];
        List<Adopter__c> adoptersToUpdate = new List<Adopter__c>();

        for (Adopter__c adopter : adoptersList){
            adopter.Warning__c = flag;
            adoptersToUpdate.add(adopter);
        }
        
        update adoptersToUpdate;
    }

    // Runs the class
    public static void run(List<Adoption__c> listAdp, String filter, boolean flag){

        List<Adoption__c> runAdoptions = adoptionFilter(listAdp, filter);
        marksAdopterWarning(runAdoptions, flag);
    }

}